### ISSUE TITLE
Line 123 needs another ) at the end

### ISSUE THREAD

**Issue by longoriaCS** [DAA-0101/CSFinal_DAA-0101#1]
https://github.com/DAA-0101/CSFinal_DAA-0101/blob/efa4b93707a8b7cdeea3d3506afe3ff5dd7a2791/snake_game_code.py#L123

Not sure if you've caught this already, but needs a final ) at the end, gives a syntax error otherwise.

**Comment by DAA-0101** [comment]
Thank you, I changed it

**Comment by longoriaCS** [comment]
Is this your final code? Or still working on it?

**Comment by DAA-0101** [comment]
Its the final code
